### PR TITLE
Changed filenames, added Bulma standard  to components, organizing cs…

### PR DESCRIPTION
**Pull request by lalaya**
- Changed all components files to index.js
- Added Bumla classes to components
- Our side is now responsive except footer input
- Start working on CSS structure

### CODE REVIEW

**Comment by lalaya** [comment]
Closed pull request to add some motifications.

**Comment by HimonRana** [comment]
Indentation is not done yet, please check again dear Laya.

**Comment by lalaya** [comment]
Removed a spacing to see if indentation now uploads correctly at github.

**Comment by lalaya** [comment]
Trying again.

**Comment by lalaya** [comment]
Changed tabs and space in settings to see if this works.

**Pull request merged**
